name: Generate contribution snake

on:
  workflow_dispatch:
  schedule:
    - cron: "41 3 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v6

      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: TarunB-Git
          outputs: |
            profile/github-snake.svg
            profile/github-snake-dark.svg?palette=github-dark

      - name: Save updated snake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/github-snake.svg profile/github-snake-dark.svg

          if git diff --cached --quiet; then
            echo "Nothing changed."
            exit 0
          fi

          git commit -m "Update contribution snake"
          git push
